### PR TITLE
fix precedence when default value is non-empty

### PR DESCRIPTION
**Pull request by halberom**
This fixes the case where a module label is instantiated with a
non-default delimiter, and then another label is generated based off the
context but uses the default delimiter as the local var takes
precedence.

The only case this actually applies to is the delimiter, which has a
default value of '-', however all others changed to make them
consistent.

tested with
- terraform fmt
- terraform validate
- including as source in project

### CODE REVIEW

**Comment by halberom** [comment]
more information
```
variable "delimiter" {
  default = "."
}
variable "attributes" {
  default = []
}
variable "environment" {
  default = "dev"
}
variable "label_order" {
  default = ["attributes", "name", "stage", "environment", "namespace"]
}
variable "name" {
  default = "widget"
}
variable "namespace" {
  default = "example"
}
variable "stage" {
  default = ""
}
variable "tags" {
  default = []
}
module "label" {
  source = "/git/github.com/halberom/terraform-null-label"
  attributes  = "${var.attributes}"
  delimiter   = "${var.delimiter}"
  environment = "${var.environment}"
  label_order = "${var.label_order}"
  name        = "${var.name}"
  namespace   = "${var.namespace}"
  stage       = "${var.stage}"
  tags        = "${var.tags}"
}

module "s3_bucket_label" {
  source = "/git/github.com/halberom/terraform-null-label"
  attributes = ["state"]
  context    = "${module.label.context}"
}
```
without this change, output of the s3_bucket_label is
```
module.label.id = widget.dev.example
module.s3_bucket_label.id = state-widget-dev-example # note the incorrect delimiter
```
with the change
```
module.label.id = widget.dev.example
module.s3_bucket_label.id = state.widget.dev.example
```

**Comment by halberom** [comment]
The one problem with this is that if someone sets their delimiter to a different value, e.g. `.`, but then needs to change it in a context label, e.g. for a kms alias which doesn't allow `.`, then if they want to use `-` it won't work because it'll match the delimiter default in this module and this change will make the context value take precedence.  Not sure what to do for that.

**Comment by aknysh** [comment]
@halberom  thank you for the PR
It looks good and ready to merge, but I found a race condition when calculating `attributes` with a non-default `delimiter`. It present in both `master` code and yours.
Will try to resolve it.

**Comment by aknysh** [comment]
@halberom 
I tested the code, it works OK.
Will merge your PR into master and then open another one with the race condition fixes (since it's not related to the changes you made).
thanks

**Comment by halberom** [comment]
@aknysh - thanks, did you have any thoughts on my comment about overriding a context delimiter?  i.e. 

1. module label has delimiter `.`
2. module foo_label gets context from module label, but overrides delimiter with `-`.  with this PR change, that won't happen, because it'll be the same as the default so the context will take precedence.

The only way I can see to fix it (without an override flag) is to remove the default delimiter value so it's empty, and set it in locals.  But that could be a bit confusing to people.

**Comment by aknysh** [comment]
@halberom 
I see what you are saying.
I think it's such an edge case that we should not introduce any additional complexity into the module.
`context` is not really necessary to use in majority of use-cases, it's easy to provide the same input vars to a few labels in a module.

**Pull request merged**
