### PR TITLE
Terraform 0.14 upgrade

### PR DESCRIPTION
**Pull request by maximmi**
## what
- Upgrade to support Terraform 0.14 and bring up to current Cloud Posse standard

## why
- Support Terraform 0.14

### CODE REVIEW

**Review by Nuru — CHANGES_REQUESTED** [review]
@osterman I think `terraform-null-label` should not be using these automated workflows. `auto-context` is self-referential. `auto-release` should keep `publish: false`, etc. The consequences of `renovate` update and auto-merge should be reviewed before we start the ripple effect caused by updating this module.

**Comment by codeaprendiz** [comment]
Hiii amazing folks :),
When are we merging this PR ? We want to upgrade to terraform version 0.14.2 as well.

**Comment by BlackWebWolf** [comment]
Bump, as we also are quite interested in using it with newest terraform :)

**Comment by osterman** [comment]
@maximmi I think we should close this one has it's very self-referential and the module already supports 0.14

**Pull request closed without merging**
